### ISSUE TITLE
Windows Build failed on cargo install pax-cli

### ISSUE THREAD

**Issue by Distil62** [paxdotdev/pax#267]
Hello,
Rust verstion : `rustc 1.81.0 (eeb90cda1 2024-09-04)`
Windows version : `Microsoft Windows 11 Entreprise - 10.0.22631 Build 22631`
When I follow the instructions on this page https://docs.pax.dev/installation/operating-systems/windows/, the `pax-compiler` library fails to compile.

The error: `error[E0433]: failed to resolve: could not find unix in os`
`.cargo\registry\src\index.crates.io-6f17d22bba15001f\pax-compiler-0.36.6\src\design_server\websocket.rs:18:14`

![image](https://github.com/user-attachments/assets/1dbbb4d9-af6c-4fe7-9fab-0de1fe825650)

Am I missing something in my system?

**Comment by zackbrown** [comment]
Thanks for the report!  `pax-compiler#design_server` is a new module and it appears to be breaking pax-cli builds on Windows workstations; this is prioritized and we will follow up here when fixed.

**Comment by samuelselleck** [comment]
@Distil62 We've deployed a new version of pax-cli that should have fixed the windows issues you are seeing.

Do let us know if you bump into any other roadblocks, it's really useful for us to know!

**Comment by Distil62** [comment]
It's work now! Thank for your work :)
